name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "15 * * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read/write
  
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Auto green
        run: |
          git config --local user.email "31774289+TylerTurner-225@users.noreply.github.com"
          git config --local user.name "Tyler Turner"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push
